name: 🧪 Test snap can be built on x86_64

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '!src/osx/**'
      - '!src/freebsd/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/continuous-build-linux.yml'    
  pull_request:
    branches: [ main ]
    tags-ignore:
      - '*.*'      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
      - uses: actions/checkout@v2

      - uses: snapcore/action-build@v1
        id: build

      - uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.build.outputs.snap }}
          isClassic: 'false'
